# Generated by Django 4.2.30 on 2026-05-11 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_captures', models.PositiveIntegerField(default=0)),
                ('good_postures', models.PositiveIntegerField(default=0)),
                ('bad_postures', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadísticas de usuario',
            },
        ),
        migrations.CreateModel(
            name='PostureCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Etiqueta mostrada')),
                ('raw_prediction', models.CharField(default='', max_length=50, verbose_name='Predicción del modelo')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confianza (%)')),
                ('status', models.CharField(choices=[('good', 'Buena postura'), ('danger', 'Postura mala'), ('unknown', 'Sin determinar')], default='unknown', max_length=20)),
                ('color', models.CharField(default='#6b7280', max_length=10)),
                ('landmarks_detected', models.BooleanField(default=False)),
                ('in_profile', models.BooleanField(default=False, verbose_name='En perfil correcto')),
                ('ang_espalda', models.FloatField(blank=True, null=True, verbose_name='Ángulo espalda')),
                ('ang_cuello', models.FloatField(blank=True, null=True, verbose_name='Ángulo cuello')),
                ('inclinacion', models.FloatField(blank=True, null=True, verbose_name='Inclinación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='captures/%Y/%m/%d/')),
                ('annotated_img', models.ImageField(blank=True, null=True, upload_to='annotated/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captura de postura',
                'verbose_name_plural': 'Capturas de postura',
                'ordering': ['-created_at'],
            },
        ),
    ]
